version: "3.8"

services:
    apache:
        build: './apache'
        volumes:
            - ./symfony:/var/www/html
        ports:
        -   '3000:80'
    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        volumes:
            - ./symfony:/var/www/html
        user: '1000'
    postgresql:
        image: postgres:13
        restart: always
        ports:
        - '5432:5432'
        env_file:
            -   ./env/postgresql.env
    composer:
        build: ./composer
        volumes:
            - ./symfony:/var/www/html
    node:
      build: './node'
      working_dir: /home/node/app
      volumes:
        - ./symfony:/home/node/app
      user: '1000'

